### ISSUE TITLE
About include error

### ISSUE THREAD

**Issue by abhid95** [skandhurkat/EmoDetect#1]
ubuntu@ubuntu-HP-15-Notebook-PC:~/Desktop/EmoDetect-master/src$ g++ demo.cpp
demo.cpp:31:47: fatal error: FeatureExtractors/extractFeatures.h: No such file or directory
 #include <FeatureExtractors/extractFeatures.h>
                                               ^
compilation terminated.

Can u please tell where is extractFeatures.h file ?
Its not there in FeatureExtractors folder can u please provide it.

**Comment by skandhurkat** [comment]
The file is in `include/FeatureExtractors`.

Please do not use GCC directly to compile. Use the CMake build system to generate a Makefile or IDE project which will set the correct paths for you.
